name: arrow_client
description: "Client app for CAR SERVER"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  auto_route: ^8.3.0
  camera: ^0.11.0+1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.5.0+1
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  image: ^4.2.0
  injectable: ^2.4.4
  json_annotation: ^4.9.0
  path_provider: ^2.1.3

dev_dependencies:
  auto_route_generator: ^8.1.0
  build_runner: ^2.4.11

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
